name = "mackerel-mcp"
main = "src/index.ts"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[vars]
DEV_PORT = "8788"
BASE_URL = "localhost:8788"

[observability]
enabled = true

[dev]
port = 8788
